// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// psi
double psi(double y, double k);
RcppExport SEXP RobustHoltWinters_psi(SEXP ySEXP, SEXP kSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< double >::type y(ySEXP );
        Rcpp::traits::input_parameter< double >::type k(kSEXP );
        double __result = psi(y, k);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// RobustHoltWintersCpp
List RobustHoltWintersCpp(NumericVector x, const double alpha, const double beta, const double gamma, int startTime, int seasonalType, int frequency, double levelInitial, double trendInitial, NumericVector seasonInitial, double sigma, double k);
RcppExport SEXP RobustHoltWinters_RobustHoltWintersCpp(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP startTimeSEXP, SEXP seasonalTypeSEXP, SEXP frequencySEXP, SEXP levelInitialSEXP, SEXP trendInitialSEXP, SEXP seasonInitialSEXP, SEXP sigmaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP );
        Rcpp::traits::input_parameter< const double >::type beta(betaSEXP );
        Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP );
        Rcpp::traits::input_parameter< int >::type startTime(startTimeSEXP );
        Rcpp::traits::input_parameter< int >::type seasonalType(seasonalTypeSEXP );
        Rcpp::traits::input_parameter< int >::type frequency(frequencySEXP );
        Rcpp::traits::input_parameter< double >::type levelInitial(levelInitialSEXP );
        Rcpp::traits::input_parameter< double >::type trendInitial(trendInitialSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type seasonInitial(seasonInitialSEXP );
        Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP );
        Rcpp::traits::input_parameter< double >::type k(kSEXP );
        List __result = RobustHoltWintersCpp(x, alpha, beta, gamma, startTime, seasonalType, frequency, levelInitial, trendInitial, seasonInitial, sigma, k);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
