# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

psi <- function(x) {
    .Call('RobustHoltWinters_psi', PACKAGE = 'RobustHoltWinters', x)
}

RobustHoltWintersCpp <- function(x, alpha, beta, gamma, startTime, frequency, levelInitial, trendInitial, seasonInitial, sigma, st) {
    .Call('RobustHoltWinters_RobustHoltWintersCpp', PACKAGE = 'RobustHoltWinters', x, alpha, beta, gamma, startTime, frequency, levelInitial, trendInitial, seasonInitial, sigma, st)
}

