# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

psi <- function(y, k) {
    .Call('RobustHoltWinters_psi', PACKAGE = 'RobustHoltWinters', y, k)
}

RobustHoltWintersCpp <- function(x, alpha, beta, gamma, startTime, seasonalType, frequency, doTrend, doSeasonal, levelInitial, trendInitial, seasonInitial, sigma, k) {
    .Call('RobustHoltWinters_RobustHoltWintersCpp', PACKAGE = 'RobustHoltWinters', x, alpha, beta, gamma, startTime, seasonalType, frequency, doTrend, doSeasonal, levelInitial, trendInitial, seasonInitial, sigma, k)
}

